#pragma once

// Freedom Clock — Quote Database
// Total entries: see QUOTE_DB_COUNT below
// Sections: Time | Stoicism | Financial Freedom | Bitcoin & Sound Money |
//           Freedom | Purpose & Meaning | Action & Courage |
//           Living Fully & Happiness | Philosophy & Wisdom | Simplicity & Self-Reliance

struct QuoteEntry {
  const char* text;
  const char* author;
};

static const QuoteEntry QUOTE_DB[] = {

  // ─── TIME & ITS VALUE ────────────────────────────────────────────────────

  {"Time is more valuable than money. You can get more money, but you cannot get more time.", "Jim Rohn"},
  {"The price of anything is the amount of life you exchange for it.", "Henry David Thoreau"},
  {"Time is the wisest counselor of all.", "Pericles"},
  {"Lost time is never found again.", "Benjamin Franklin"},
  {"You may delay, but time will not.", "Benjamin Franklin"},
  {"Since thou art not sure of a minute, throw not away an hour.", "Benjamin Franklin"},
  {"Dost thou love life? Then do not squander time, for that is the stuff life is made of.", "Benjamin Franklin"},
  {"Time you enjoy wasting is not wasted time.", "Marthe Troly-Curtin"},
  {"The present moment always will have been.", "Unknown"},
  {"Begin at once to live, and count each separate day as a separate life.", "Seneca"},
  {"Don't count the days. Make the days count.", "Muhammad Ali"},
  {"It is not that we have a short time to live, but that we waste much of it.", "Seneca"},
  {"While we are postponing, life speeds by.", "Seneca"},
  {"The greatest obstacle to living is expectancy, which hangs upon tomorrow and loses today.", "Seneca"},
  {"Life is long if you know how to use it.", "Seneca"},
  {"You live as if you were destined to live forever; no thought of your frailty ever enters your head.", "Seneca"},
  {"People are frugal in guarding their personal property; but as soon as it comes to squandering time they are most wasteful of the one thing in which it is right to be stingy.", "Seneca"},
  {"How we spend our days is how we spend our lives.", "Annie Dillard"},
  {"The impulse to save something good for a better place later is the signal to spend it now.", "Annie Dillard"},
  {"The bad news is time flies. The good news is you are the pilot.", "Michael Altshuler"},
  {"The two most powerful warriors are patience and time.", "Leo Tolstoy"},
  {"Time is free, but it is priceless. You cannot own it, but you can use it.", "Harvey MacKay"},
  {"You could leave life right now. Let that determine what you do and say and think.", "Marcus Aurelius"},
  {"It is not death that a man should fear, but he should fear never beginning to live.", "Marcus Aurelius"},
  {"Do not act as if you were going to live ten thousand years. Death hangs over you. While you live, while it is in your power, be good.", "Marcus Aurelius"},
  {"As if you could kill time without injuring eternity.", "Henry David Thoreau"},
  {"Your time is limited, so don't waste it living someone else's life.", "Steve Jobs"},
  {"Remembering that I'll be dead soon is the most important tool I've ever encountered to help me make the big choices in life.", "Steve Jobs"},
  {"Death is very likely the single best invention of life. It clears out the old to make way for the new.", "Steve Jobs"},
  {"Relentlessly prune bullshit, don't wait to do things that matter, and savor the time you have.", "Paul Graham"},
  {"If life is short, we should expect its shortness to take us by surprise. And that is just what tends to happen.", "Paul Graham"},


  // ─── STOICISM ────────────────────────────────────────────────────────────

  {"You have power over your mind, not outside events. Realize this, and you will find strength.", "Marcus Aurelius"},
  {"Waste no more time arguing about what a good man should be. Be one.", "Marcus Aurelius"},
  {"The happiness of your life depends upon the quality of your thoughts.", "Marcus Aurelius"},
  {"If you are distressed by anything external, the pain is not due to the thing itself, but to your estimate of it; and this you have the power to revoke at any moment.", "Marcus Aurelius"},
  {"Never let the future disturb you. You will meet it, if you have to, with the same weapons of reason which today arm you against the present.", "Marcus Aurelius"},
  {"Confine yourself to the present.", "Marcus Aurelius"},
  {"Very little is needed to make a happy life; it is all within yourself, in your way of thinking.", "Marcus Aurelius"},
  {"The best revenge is to be unlike him who performed the injury.", "Marcus Aurelius"},
  {"The impediment to action advances action. What stands in the way becomes the way.", "Marcus Aurelius"},
  {"We suffer more in imagination than in reality.", "Seneca"},
  {"It is not the man who has too little, but the man who craves more, that is poor.", "Seneca"},
  {"As long as you live, keep learning how to live.", "Seneca"},
  {"Sometimes even to live is an act of courage.", "Seneca"},
  {"True happiness is to enjoy the present, without anxious dependence upon the future.", "Seneca"},
  {"You act like mortals in all that you fear, and like immortals in all that you desire.", "Seneca"},
  {"It is not that we have a short time to live, but that we waste a lot of it.", "Lucius Annaeus Seneca"},
  {"No man is free who is not master of himself.", "Epictetus"},
  {"Men are disturbed not by the things which happen, but by the opinions about the things.", "Epictetus"},
  {"Make the best use of what is in your power, and take the rest as it happens.", "Epictetus"},
  {"First say to yourself what you would be; and then do what you have to do.", "Epictetus"},
  {"Wealth consists not in having great possessions, but in having few wants.", "Epictetus"},
  {"He is a wise man who does not grieve for the things which he has not, but rejoices for those which he has.", "Epictetus"},
  {"How long are you going to wait before you demand the best for yourself?", "Epictetus"},
  {"If it is not right, do not do it. If it is not true, do not say it.", "Marcus Aurelius"},
  {"Seek freedom and become captive of your desires. Seek discipline and find your liberty.", "Frank Herbert"},
  {"He is richest who is content with the least.", "Socrates"},
  {"Frugality includes all the other virtues.", "Cicero"},
  {"He who is not contented with what he has would not be contented with what he would like to have.", "Socrates"},
  {"Discipline equals freedom.", "Jocko Willink"},
  {"Don't expect to be motivated every day to get out there and make things happen. Count on discipline.", "Jocko Willink"},


  // ─── FINANCIAL FREEDOM & INVESTING ──────────────────────────────────────

  {"The goal isn't more money. The goal is living life on your own terms.", "Chris Brogan"},
  {"Financial freedom is available to those who learn about it and work for it.", "Robert Kiyosaki"},
  {"The most dangerous risk of all is spending your life not doing what you want, betting you can buy yourself freedom later.", "Randy Komisar"},
  {"Do not save what is left after spending, but spend what is left after saving.", "Warren Buffett"},
  {"If you don't find a way to make money while you sleep, you will work until you die.", "Warren Buffett"},
  {"It's not how much money you make, but how much you keep and how hard it works for you.", "Robert Kiyosaki"},
  {"Real wealth is not having to go to meetings, not spending time with jerks, not feeling like your life is passing you by.", "Naval Ravikant"},
  {"Financial freedom is less about money and more about options.", "Unknown"},
  {"The difference between rich and wealthy is time.", "Unknown"},
  {"Owning investments is freedom. A job is a golden cage.", "Unknown"},
  {"Every time you borrow money, you are robbing your future self.", "Nathan W. Morris"},
  {"Beware of little expenses. A small leak will sink a great ship.", "Benjamin Franklin"},
  {"A penny saved is a penny earned.", "Benjamin Franklin"},
  {"An investment in knowledge pays the best interest.", "Benjamin Franklin"},
  {"A budget is telling your money where to go instead of wondering where it went.", "Dave Ramsey"},
  {"Compound interest is the eighth wonder of the world. He who understands it, earns it.", "Albert Einstein"},
  {"The stock market transfers money from the impatient to the patient.", "Warren Buffett"},
  {"Risk comes from not knowing what you are doing.", "Warren Buffett"},
  {"The best investment you can make is in yourself.", "Warren Buffett"},
  {"Never depend on a single income. Make investments to create a second source.", "Warren Buffett"},
  {"Rule No. 1: Never lose money. Rule No. 2: Never forget rule No. 1.", "Warren Buffett"},
  {"Be fearful when others are greedy, and greedy when others are fearful.", "Warren Buffett"},
  {"Price is what you pay. Value is what you get.", "Warren Buffett"},
  {"Our favorite holding period is forever.", "Warren Buffett"},
  {"Someone is sitting in the shade today because someone planted a tree a long time ago.", "Warren Buffett"},
  {"The more you learn, the more you earn.", "Warren Buffett"},
  {"Formal education will make you a living. Self-education will make you a fortune.", "Jim Rohn"},
  {"Spend each day trying to be a little wiser than you were when you woke up.", "Charlie Munger"},
  {"The big money is not in the buying or the selling, but in the waiting.", "Charlie Munger"},
  {"Live within your income and save so that you can invest.", "Charlie Munger"},
  {"Invert, always invert.", "Charlie Munger"},
  {"The first rule of a happy life is low expectations.", "Charlie Munger"},
  {"The individual investor should act consistently as an investor, not as a speculator.", "Benjamin Graham"},
  {"Money is a great servant but a bad master.", "Francis Bacon"},
  {"A wise person should have money in their head, but not in their heart.", "Jonathan Swift"},
  {"He who lives by the crystal ball will eat shattered glass.", "Ray Dalio"},
  {"Cash is trash.", "Ray Dalio"},
  {"Pain plus reflection equals progress.", "Ray Dalio"},
  {"Inflation is taxation without legislation.", "Milton Friedman"},
  {"Nobody spends somebody else's money as carefully as he spends his own.", "Milton Friedman"},
  {"A society that puts equality before freedom will get neither. A society that puts freedom before equality will get a high degree of both.", "Milton Friedman"},
  {"Underlying most arguments against the free market is a lack of belief in freedom itself.", "Milton Friedman"},
  {"Gold has intrinsic value. The problem with the dollar is it has no intrinsic value.", "Peter Schiff"},
  {"Gold is the money of kings, silver of gentlemen, barter of peasants, and debt is the money of slaves.", "Norm Franz"},
  {"Gold is money. Everything else is credit.", "J.P. Morgan"},
  {"If you want to be rich, think of saving as earning.", "Andrew Carnegie"},
  {"Rich people have big libraries. Poor people have big TVs.", "Zig Ziglar"},
  {"Financial peace isn't the acquisition of stuff. It is learning to live on less than you make.", "Dave Ramsey"},
  {"The real measure of your wealth is how much you would be worth if you lost all your money.", "Unknown"},
  {"He who buys what he does not need, steals from himself.", "Swedish Proverb"},
  {"Money is only a tool. It will take you wherever you wish, but it will not replace you as the driver.", "Ayn Rand"},
  {"So you think that money is the root of all evil? Have you ever asked what is the root of money?", "Ayn Rand"},
  {"Money is the material shape of the principle that men who wish to deal with one another must deal by trade and give value for value.", "Ayn Rand"},
  {"All the returns in life, whether in wealth, relationships, or knowledge, come from compound interest.", "Naval Ravikant"},


  // ─── BITCOIN, SOUND MONEY & MONETARY SOVEREIGNTY ────────────────────────

  {"The root problem with conventional currency is all the trust that's required to make it work.", "Satoshi Nakamoto"},
  {"The central bank must be trusted not to debase the currency, but the history of fiat currencies is full of breaches of that trust.", "Satoshi Nakamoto"},
  {"Lost coins only make everyone else's coins worth slightly more. Think of it as a donation to everyone.", "Satoshi Nakamoto"},
  {"If you don't believe me or don't get it, I don't have time to try to convince you, sorry.", "Satoshi Nakamoto"},
  {"It might make sense just to get some in case it catches on. If enough people think the same way, that becomes a self fulfilling prophecy.", "Satoshi Nakamoto"},
  {"Writing a description for this thing for general audiences is bloody hard. There's nothing to relate it to.", "Satoshi Nakamoto"},
  {"Running bitcoin.", "Hal Finney"},
  {"I see Bitcoin as ultimately becoming a reserve currency for banks, playing much the same role as gold did in the early days of banking.", "Hal Finney"},
  {"The computer can be used as a tool to liberate and protect people, rather than to control them.", "Hal Finney"},
  {"Trusted third parties are security holes.", "Nick Szabo"},
  {"The secret to Bitcoin's success is certainly not its computational efficiency or its scalability — it is its social scalability.", "Nick Szabo"},
  {"Bitcoin is a swarm of cyber hornets serving the goddess of wisdom, feeding on the fire of truth, exponentially growing ever smarter, faster, and stronger behind a wall of encrypted energy.", "Michael Saylor"},
  {"Bitcoin is digital energy. With this technology we can deliver any amount of power, at any frequency, anywhere in time and space, with nearly zero friction.", "Michael Saylor"},
  {"Bitcoin — There Is No Second Best.", "Michael Saylor"},
  {"There is no second best.", "Michael Saylor"},
  {"You do not sell your Bitcoin.", "Michael Saylor"},
  {"Bitcoin is a bank in cyberspace, run by incorruptible software, offering a global, affordable, simple, and secure savings account to billions of people that don't have the option or desire to run their own hedge fund.", "Michael Saylor"},
  {"If you aren't willing to own bitcoin for 10 years, don't even think about owning it for 10 minutes.", "Michael Saylor"},
  {"Bitcoin is money. Everything else is credit.", "Michael Saylor"},
  {"Capitalism is what happens when people drop their time preference, defer immediate gratification, and invest in the future.", "Saifedean Ammous"},
  {"Bitcoin is the hardest money ever invented: growth in its value cannot possibly increase its supply; it can only make the network more secure and immune to attack.", "Saifedean Ammous"},
  {"Your keys, your Bitcoin. Not your keys, not your Bitcoin.", "Andreas Antonopoulos"},
  {"Bitcoin is the internet of money. Currency is only the first application.", "Andreas Antonopoulos"},
  {"Bitcoin is the separation of money and state.", "Robert Breedlove"},
  {"Money is the language of human action.", "Robert Breedlove"},
  {"Bitcoin will not be eagerly adopted by the mainstream, it will be forced upon them — compelled by economic reality.", "Pierre Rochard"},
  {"The world ultimately will have a single currency. The internet will have a single currency. I personally believe that it will be bitcoin.", "Jack Dorsey"},
  {"Bitcoin changes absolutely everything. I don't think there is anything more important in my lifetime to work on.", "Jack Dorsey"},
  {"Bitcoin is the most significant monetary advance since the creation of coinage.", "Edward Snowden"},
  {"Privacy is necessary for an open society in the electronic age. Privacy is the power to selectively reveal oneself to the world.", "Eric Hughes"},
  {"Cypherpunks write code. We know that someone has to write software to defend privacy, and since we can't get privacy unless we all do, we're going to write it.", "Eric Hughes"},
  {"Bitcoin is a technological tour de force.", "Bill Gates"},
  {"Saving in a hard currency is the most powerful wealth-building tool available to ordinary people.", "Unknown"},
  {"Not your keys, not your coins.", "Unknown"},
  {"Bitcoin is the exit.", "Unknown"},
  {"Sound money is a prerequisite for individual freedom.", "Unknown"},
  {"The halving is not an event, it is a reminder that scarcity matters.", "Unknown"},
  {"It is impossible to grasp the meaning of the idea of sound money if one does not realize that it was devised as an instrument for the protection of civil liberties against despotic inroads on the part of governments.", "Ludwig von Mises"},
  {"There is no means of avoiding the final collapse of a boom brought about by credit expansion.", "Ludwig von Mises"},
  {"The most important thing to remember is that inflation is not an act of God; inflation is a policy.", "Ludwig von Mises"},
  {"Government cannot make man richer, but it can make him poorer.", "Ludwig von Mises"},
  {"The issue is always the same: the government or the market. There is no third solution.", "Ludwig von Mises"},
  {"I don't believe we shall ever have a good money again before we take the thing out of the hands of government.", "Friedrich Hayek"},
  {"The root and source of all monetary evil is the government's monopoly on money.", "Friedrich Hayek"},
  {"We have always had bad money because private enterprise was not permitted to give us a better one.", "Friedrich Hayek"},
  {"Paper money eventually returns to its intrinsic value — zero.", "Voltaire"},
  {"It is no coincidence that the century of total war coincided with the century of central banking.", "Ron Paul"},
  {"The state is the great fiction by which everyone tries to live at the expense of everyone else.", "Frederic Bastiat"},
  {"When plunder becomes a way of life for a group of men in a society, over the course of time they create for themselves a legal system that authorizes it and a moral code that glorifies it.", "Frederic Bastiat"},
  {"Life, liberty, and property do not exist because men have made laws. On the contrary, it was the fact that life, liberty, and property existed beforehand that caused men to make laws in the first place.", "Frederic Bastiat"},
  {"I sincerely believe that banking establishments are more dangerous than standing armies; and that the principle of spending money to be paid by posterity is but swindling futurity on a large scale.", "Thomas Jefferson"},
  {"Freedom can run a monetary system as superbly as it runs the rest of the economy.", "Murray Rothbard"},
  {"Never give up on a dream because of the time it will take to accomplish it. The time will pass anyway.", "Earl Nightingale"},


  // ─── FREEDOM ─────────────────────────────────────────────────────────────

  {"Freedom is not the absence of commitments, but the ability to choose what you commit to.", "Paulo Coelho"},
  {"For to be free is not merely to cast off one's chains, but to live in a way that respects and enhances the freedom of others.", "Nelson Mandela"},
  {"Freedom is nothing but a chance to be better.", "Albert Camus"},
  {"Man is free at the moment he wishes to be.", "Voltaire"},
  {"Those who would give up essential Liberty, to purchase a little temporary Safety, deserve neither Liberty nor Safety.", "Benjamin Franklin"},
  {"I prefer dangerous freedom over peaceful slavery.", "Thomas Jefferson"},
  {"Liberty means responsibility. That is why most men dread it.", "George Bernard Shaw"},
  {"The secret to happiness is freedom, and the secret to freedom is courage.", "Thucydides"},
  {"Liberty and responsibility are inseparable.", "Friedrich Hayek"},
  {"Emergencies have always been the pretext on which the safeguards of individual liberty have been eroded.", "Friedrich Hayek"},
  {"The curious task of economics is to demonstrate to men how little they really know about what they imagine they can design.", "Friedrich Hayek"},
  {"A claim for equality of material position can be met only by a government with totalitarian powers.", "Friedrich Hayek"},
  {"Man is condemned to be free; because once thrown into the world, he is responsible for everything he does.", "Jean-Paul Sartre"},
  {"Man is nothing else but that which he makes of himself.", "Jean-Paul Sartre"},
  {"Anxiety is the dizziness of freedom.", "Soren Kierkegaard"},
  {"To dare is to lose one's footing momentarily. Not to dare is to lose oneself.", "Soren Kierkegaard"},
  {"Governments of the Industrial World, you weary giants of flesh and steel: you have no sovereignty where we gather.", "John Perry Barlow"},
  {"We are creating a world where anyone, anywhere may express his or her beliefs, no matter how singular, without fear of being coerced into silence or conformity.", "John Perry Barlow"},
  {"A specter is haunting the modern world, the specter of crypto anarchy.", "Timothy May"},
  {"The only limit to our realization of tomorrow will be our doubts of today.", "Franklin D. Roosevelt"},
  {"I prefer to be true to myself, even at the hazard of incurring the ridicule of others, rather than to be false, and to incur my own abhorrence.", "Frederick Douglass"},
  {"If there is no struggle, there is no progress.", "Frederick Douglass"},
  {"Escape competition through authenticity.", "Naval Ravikant"},
  {"Happiness is a state where nothing is missing.", "Naval Ravikant"},
  {"The time is always right to do what is right.", "Martin Luther King Jr."},


  // ─── PURPOSE & MEANING ───────────────────────────────────────────────────

  {"The two most important days in your life are the day you are born and the day you find out why.", "Mark Twain"},
  {"Tell me, what is it you plan to do with your one wild and precious life?", "Mary Oliver"},
  {"The purpose of life is to live it, to taste experience to the utmost.", "Eleanor Roosevelt"},
  {"The only way to do great work is to love what you do.", "Steve Jobs"},
  {"Stay hungry. Stay foolish.", "Steve Jobs"},
  {"The greatest use of a life is to spend it on something that will outlast it.", "William James"},
  {"The greatest discovery of my generation is that a human being can alter his life by altering his attitudes.", "William James"},
  {"He who has a why to live for can bear almost any how.", "Friedrich Nietzsche"},
  {"Too many people die with their music still in them.", "Oliver Wendell Holmes"},
  {"Do not go where the path may lead. Go instead where there is no path and leave a trail.", "Ralph Waldo Emerson"},
  {"The meaning of life is to find your gift. The purpose of life is to give it away.", "Pablo Picasso"},
  {"What you get by achieving your goals is not as important as what you become.", "Zig Ziglar"},
  {"The only person you are destined to become is the person you decide to be.", "Ralph Waldo Emerson"},
  {"It takes courage to grow up and become who you really are.", "E.E. Cummings"},
  {"Everything can be taken from a man but one thing: the last of the human freedoms — to choose one's attitude in any given set of circumstances, to choose one's own way.", "Viktor Frankl"},
  {"When we are no longer able to change a situation, we are challenged to change ourselves.", "Viktor Frankl"},
  {"Suffering ceases to be suffering at the moment it finds a meaning.", "Viktor Frankl"},
  {"It did not really matter what we expected from life, but rather what life expected from us.", "Viktor Frankl"},
  {"Life is never made unbearable by circumstances, but only by lack of meaning and purpose.", "Viktor Frankl"},
  {"The privilege of a lifetime is to become who you truly are.", "Carl Jung"},
  {"Your vision will become clear only when you can look into your own heart. Who looks outside, dreams; who looks inside, awakes.", "Carl Jung"},
  {"Life can only be understood backwards; but it must be lived forwards.", "Soren Kierkegaard"},
  {"The unexamined life is not worth living.", "Socrates"},
  {"The life of the dead is placed in the memory of the living.", "Cicero"},
  {"The value of life lies not in the length of days, but in the use we make of them.", "Michel de Montaigne"},
  {"The great use of life is to spend it for something that will outlast it.", "William James"},
  {"The deeper that sorrow carves into your being, the more joy you can contain.", "Khalil Gibran"},
  {"Work is love made visible.", "Khalil Gibran"},
  {"Knowledge can be communicated, but not wisdom. One can find it, live it, do wonders through it, but one cannot communicate and teach it.", "Hermann Hesse"},
  {"The mystery of human existence lies not in just staying alive, but in finding something to live for.", "Fyodor Dostoevsky"},
  {"This is the real secret of life — to be completely engaged with what you are doing in the here and now. And instead of calling it work, realize it is play.", "Alan Watts"},
  {"The future belongs to those who believe in the beauty of their dreams.", "Eleanor Roosevelt"},
  {"I knew that if I failed I wouldn't regret that, but I knew the one thing I might regret is not ever having tried.", "Jeff Bezos"},


  // ─── ACTION, COURAGE & MOTIVATION ────────────────────────────────────────

  {"The secret to getting ahead is getting started.", "Mark Twain"},
  {"Action is the foundational key to all success.", "Pablo Picasso"},
  {"If not now, when?", "Hillel the Elder"},
  {"You don't have to be great to start, but you have to start to be great.", "Zig Ziglar"},
  {"Stop being afraid of what could go wrong, and start being excited about what could go right.", "Tony Robbins"},
  {"The price of inaction is far greater than the cost of making a mistake.", "Meister Eckhart"},
  {"Twenty years from now you will be more disappointed by the things you didn't do.", "Mark Twain"},
  {"What we fear doing most is usually what we most need to do.", "Timothy Ferriss"},
  {"Every morning you have two choices: continue to sleep with your dreams, or wake up and chase them.", "Unknown"},
  {"You cannot escape the responsibility of tomorrow by evading it today.", "Abraham Lincoln"},
  {"The biggest adventure you can take is to live the life of your dreams.", "Oprah Winfrey"},
  {"Success is not final, failure is not fatal. It is the courage to continue that counts.", "Winston Churchill"},
  {"We are what we repeatedly do. Excellence is not an act, but a habit.", "Aristotle"},
  {"Never give in — never, never, never, never — in nothing great or small, large or petty, never give in except to convictions of honour and good sense.", "Winston Churchill"},
  {"Courage is rightly esteemed the first of human qualities, because it is the quality which guarantees all others.", "Winston Churchill"},
  {"I learned that courage was not the absence of fear, but the triumph over it. The brave man is not he who does not feel afraid, but he who conquers that fear.", "Nelson Mandela"},
  {"It always seems impossible until it's done.", "Nelson Mandela"},
  {"It is not the critic who counts; not the man who points out how the strong man stumbles. The credit belongs to the man who is actually in the arena.", "Theodore Roosevelt"},
  {"Far better is it to dare mighty things, to win glorious triumphs, even though checkered by failure, than to rank with those poor spirits who live in the gray twilight that knows not victory nor defeat.", "Theodore Roosevelt"},
  {"Whatever you can do or dream you can, begin it. Boldness has genius, power, and magic in it.", "Johann Wolfgang von Goethe"},
  {"Knowing is not enough; we must apply. Willing is not enough; we must do.", "Johann Wolfgang von Goethe"},
  {"Take the first step in faith. You don't have to see the whole staircase, just take the first step.", "Martin Luther King Jr."},
  {"He who is not courageous enough to take risks will accomplish nothing in life.", "Muhammad Ali"},
  {"Champions aren't made in gyms. Champions are made from something they have deep inside them — a desire, a dream, a vision.", "Muhammad Ali"},
  {"Without commitment, you'll never start, but more importantly, without consistency, you'll never finish.", "Denzel Washington"},
  {"Don't stop when you're tired. Stop when you're done.", "David Goggins"},
  {"One must still have chaos in oneself to be able to give birth to a dancing star.", "Friedrich Nietzsche"},
  {"The secret of reaping the greatest fruitfulness and the greatest enjoyment from existence is to live dangerously!", "Friedrich Nietzsche"},
  {"That which does not kill us makes us stronger.", "Friedrich Nietzsche"},
  {"Action may not always bring happiness, but there is no happiness without action.", "Benjamin Disraeli"},
  {"Strength does not come from physical capacity. It comes from an indomitable will.", "Mahatma Gandhi"},
  {"I fear not the man who has practiced 10,000 kicks once, but I fear the man who has practiced one kick 10,000 times.", "Bruce Lee"},
  {"Be water, my friend.", "Bruce Lee"},
  {"In the midst of chaos, there is also opportunity.", "Sun Tzu"},
  {"Victorious warriors win first and then go to war, while defeated warriors go to war first and then seek to win.", "Sun Tzu"},
  {"Today is victory over yourself of yesterday; tomorrow is your victory over lesser men.", "Miyamoto Musashi"},
  {"When something is important enough, you do it even if the odds are not in your favor.", "Elon Musk"},
  {"Failure is an option here. If things are not failing, you are not innovating enough.", "Elon Musk"},
  {"Brilliant thinking is rare, but courage is in even shorter supply than genius.", "Peter Thiel"},
  {"What important truth do very few people agree with you on?", "Peter Thiel"},
  {"Given a 10 percent chance of a 100 times payoff, you should take that bet every time.", "Jeff Bezos"},


  // ─── LIVING FULLY & HAPPINESS ────────────────────────────────────────────

  {"In the end, it is not the years in your life that count. It is the life in your years.", "Abraham Lincoln"},
  {"You only live once, but if you do it right, once is enough.", "Mae West"},
  {"Life is what happens when you are busy making other plans.", "John Lennon"},
  {"Life is short, and it is here to be lived.", "Kate Winslet"},
  {"A man is not old until regrets take the place of dreams.", "John Barrymore"},
  {"Live as if you were to die tomorrow. Learn as if you were to live forever.", "Mahatma Gandhi"},
  {"Happiness is a journey, not a destination.", "Unknown"},
  {"Wealth is the ability to fully experience life.", "Henry David Thoreau"},
  {"Carpe diem. Seize the day.", "Horace"},
  {"Life should not be a journey to the grave with the intention of arriving safely in a pretty and well preserved body, but rather to skid in broadside in a cloud of smoke, thoroughly used up, totally worn out, and loudly proclaiming: Wow! What a Ride!", "Hunter S. Thompson"},
  {"My mission in life is not merely to survive, but to thrive; and to do so with some passion, some compassion, some humor, and some style.", "Maya Angelou"},
  {"You are never too old to set another goal or to dream a new dream.", "C.S. Lewis"},
  {"There are far, far better things ahead than any we leave behind.", "C.S. Lewis"},
  {"Life is no brief candle to me. It is a sort of splendid torch which I have got hold of for the moment, and I want to make it burn as brightly as possible before handing it on to future generations.", "George Bernard Shaw"},
  {"A life spent making mistakes is not only more honorable, but more useful than a life spent doing nothing.", "George Bernard Shaw"},
  {"The people who get on in this world are the people who get up and look for the circumstances they want, and if they can't find them, make them.", "George Bernard Shaw"},
  {"I wish I'd had the courage to live a life true to myself, not the life others expected of me.", "Bronnie Ware"},
  {"Health brings a freedom very few realise, until they no longer have it.", "Bronnie Ware"},
  {"Life is either a daring adventure or nothing.", "Helen Keller"},
  {"The best and most beautiful things in the world cannot be seen or even touched — they must be felt with the heart.", "Helen Keller"},
  {"Optimism is the faith that leads to achievement. Nothing can be done without hope and confidence.", "Helen Keller"},
  {"Life shrinks or expands in proportion to one's courage.", "Anais Nin"},
  {"And the day came when the risk to remain tight in a bud was more painful than the risk it took to blossom.", "Anais Nin"},
  {"To live is the rarest thing in the world. Most people exist, that is all.", "Oscar Wilde"},
  {"Be yourself. Everyone else is already taken.", "Oscar Wilde"},
  {"Doesn't everything die at last, and too soon? Tell me, what is it you plan to do with your one wild and precious life?", "Mary Oliver"},
  {"You do not have to be good. You do not have to walk on your knees for a hundred miles through the desert repenting. You only have to let the soft animal of your body love what it loves.", "Mary Oliver"},
  {"Think of all the beauty still left around you and be happy.", "Anne Frank"},
  {"As a well-spent day brings happy sleep, so a life well used brings happy death.", "Leonardo da Vinci"},
  {"People don't notice whether it's winter or summer when they're happy.", "Anton Chekhov"},
  {"I urge you to please notice when you are happy, and exclaim or murmur or think at some point: If this isn't nice, I don't know what is.", "Kurt Vonnegut"},
  {"Realize deeply that the present moment is all you ever have.", "Eckhart Tolle"},
  {"Acknowledging the good that you already have in your life is the foundation for all abundance.", "Eckhart Tolle"},
  {"There is no way to happiness — happiness is the way.", "Thich Nhat Hanh"},
  {"Happiness is not something ready made. It comes from your own actions.", "Dalai Lama"},
  {"Happiness depends upon ourselves.", "Aristotle"},
  {"You've made this day a special day, by just your being you. There's no person in the whole world like you.", "Fred Rogers"},
  {"It's not the honors and the prizes and the fancy outsides of life which ultimately nourish our souls.", "Fred Rogers"},
  {"I'm losing precious days. I am degenerating into a machine for making money. I must break away and get out into the mountains to learn the news.", "John Muir"},
  {"Keep close to Nature's heart, and break clear away, once in a while, and climb a mountain or spend a week in the woods. Wash your spirit clean.", "John Muir"},
  {"I too am not a bit tamed, I too am untranslatable, I sound my barbaric yawp over the roofs of the world.", "Walt Whitman"},
  {"I exist as I am, that is enough.", "Walt Whitman"},
  {"I do not fear death. I had been dead for billions and billions of years before I was born, and had not suffered the slightest inconvenience from it.", "Mark Twain"},
  {"Desire is a contract that you make with yourself to be unhappy until you get what you want.", "Naval Ravikant"},
  {"Smile, breathe and go slowly.", "Thich Nhat Hanh"},


  // ─── PHILOSOPHY & WISDOM ─────────────────────────────────────────────────

  {"The wound is the place where the Light enters you.", "Rumi"},
  {"Sell your cleverness and buy bewilderment.", "Rumi"},
  {"Out beyond ideas of wrongdoing and rightdoing, there is a field. I'll meet you there.", "Rumi"},
  {"Let yourself be silently drawn by the strange pull of what you really love. It will not lead you astray.", "Rumi"},
  {"You were born with wings, why prefer to crawl through life?", "Rumi"},
  {"We are what we think. All that we are arises with our thoughts. With our thoughts we make the world.", "Buddha"},
  {"Health is the greatest gift, contentment the greatest wealth, faithfulness the best relationship.", "Buddha"},
  {"Knowing others is intelligence; knowing yourself is true wisdom. Mastering others is strength; mastering yourself is true power.", "Lao Tzu"},
  {"A man with outward courage dares to die; a man with inner courage dares to live.", "Lao Tzu"},
  {"When I let go of what I am, I become what I might be.", "Lao Tzu"},
  {"Be content with what you have; rejoice in the way things are. When you realize there is nothing lacking, the whole world belongs to you.", "Lao Tzu"},
  {"He who is contented is rich.", "Lao Tzu"},
  {"He who knows others is wise; he who knows himself is enlightened.", "Lao Tzu"},
  {"No man ever steps in the same river twice, for it's not the same river and he's not the same man.", "Heraclitus"},
  {"Character is destiny.", "Heraclitus"},
  {"The first and greatest victory is to conquer yourself.", "Plato"},
  {"To know what you know and what you do not know, that is true knowledge.", "Confucius"},
  {"The man who moves a mountain begins by carrying away small stones.", "Confucius"},
  {"Everything has beauty, but not everyone sees it.", "Confucius"},
  {"He who fears he shall suffer, already suffers what he fears.", "Michel de Montaigne"},
  {"Talent hits a target no one else can hit; genius hits a target no one else can see.", "Arthur Schopenhauer"},
  {"We forfeit three-fourths of ourselves in order to be like other people.", "Arthur Schopenhauer"},
  {"Trust thyself: every heart vibrates to that iron string.", "Ralph Waldo Emerson"},
  {"A foolish consistency is the hobgoblin of little minds.", "Ralph Waldo Emerson"},
  {"Nothing can bring you peace but yourself.", "Ralph Waldo Emerson"},
  {"What lies within us is far greater than what lies behind or before us.", "Ralph Waldo Emerson"},
  {"The mass of men lead lives of quiet desperation.", "Henry David Thoreau"},
  {"I went to the woods because I wished to live deliberately, to front only the essential facts of life, and see if I could not learn what it had to teach, and not, when I came to die, discover that I had not lived.", "Henry David Thoreau"},
  {"I wanted to live deep and suck out all the marrow of life.", "Henry David Thoreau"},
  {"If a man does not keep pace with his companions, perhaps it is because he hears a different drummer. Let him step to the music which he hears, however measured or far away.", "Henry David Thoreau"},
  {"Courage is resistance to fear, mastery of fear — not absence of fear.", "Mark Twain"},
  {"Whenever you find yourself on the side of the majority, it is time to pause and reflect.", "Mark Twain"},
  {"In the depths of winter, I finally learned that within me there lay an invincible summer.", "Albert Camus"},
  {"You will never be happy if you continue to search for what happiness consists of. You will never live if you are looking for the meaning of life.", "Albert Camus"},
  {"There is only one corner of the universe you can be certain of improving, and that's your own self.", "Aldous Huxley"},
  {"To be without some of the things you want is an indispensable part of happiness.", "Bertrand Russell"},
  {"Within you there is a stillness and a sanctuary to which you can retreat at any time and be yourself.", "Hermann Hesse"},
  {"Trying to define yourself is like trying to bite your own teeth.", "Alan Watts"},
  {"The ability to observe without evaluating is the highest form of intelligence.", "Jiddu Krishnamurti"},
  {"The resilient resists shocks and stays the same; the antifragile gets better.", "Nassim Nicholas Taleb"},
  {"How much you truly believe in something can be manifested only through what you are willing to risk for it.", "Nassim Nicholas Taleb"},
  {"Every individual intends only his own gain, and he is in this, as in many other cases, led by an invisible hand to promote an end which was no part of his intention.", "Adam Smith"},
  {"It is not from the benevolence of the butcher, the brewer, or the baker that we expect our dinner, but from their regard to their own interest.", "Adam Smith"},
  {"The art of economics consists in looking not merely at the immediate but at the longer effects of any act or policy.", "Henry Hazlitt"},
  {"There is only one difference between a bad economist and a good one: the bad economist confines himself to the visible effect; the good economist takes into account both the effect that can be seen and those effects that must be foreseen.", "Frederic Bastiat"},
  {"Do not regret what you have done.", "Miyamoto Musashi"},
  {"The most important conversations you'll ever have are the ones you'll have with yourself.", "David Goggins"},
  {"Everyone thinks of changing the world, but no one thinks of changing himself.", "Leo Tolstoy"},
  {"In short, software is eating the world.", "Marc Andreessen"},
  {"Make something people want.", "Paul Graham"},
  {"The greatest obstacle to discovery is not ignorance — it is the illusion of knowledge.", "Daniel J. Boorstin"},
  {"Some people never go crazy. What truly horrible lives they must lead.", "Charles Bukowski"},


  // ─── SIMPLICITY & SELF-RELIANCE ──────────────────────────────────────────

  {"Our life is frittered away by detail. Simplify, simplify.", "Henry David Thoreau"},
  {"A man is rich in proportion to the number of things which he can afford to let alone.", "Henry David Thoreau"},
  {"Simplicity is the ultimate sophistication.", "Leonardo da Vinci"},
  {"Life, if well spent, is long.", "Leonardo da Vinci"},
  {"Whoso would be a man must be a nonconformist.", "Ralph Waldo Emerson"},
  {"A penny saved is a penny earned.", "Benjamin Franklin"},
  {"Early to bed and early to rise makes a man healthy, wealthy, and wise.", "Benjamin Franklin"},
  {"You don't have to be extreme, just consistent.", "Unknown"},
  {"The best way to find yourself is to lose yourself in the service of others.", "Mahatma Gandhi"},
  {"I am a citizen of the world.", "Diogenes"},
  {"I would much rather have men ask why I have no statue, than why I have one.", "Cato the Elder"},
  {"The secret of happiness is this: let your interests be as wide as possible, and let your reactions to the things and persons that interest you be as far as possible friendly rather than hostile.", "Bertrand Russell"},

};

static constexpr int QUOTE_DB_COUNT = (int)(sizeof(QUOTE_DB) / sizeof(QUOTE_DB[0]));
